### ISSUE TITLE
Remove synchronized keyword from getter declaration

### ISSUE THREAD

**Issue by pikol93** [Sladamos/KingdomSimulation#3]
Pola opisujące dane zwracane przez gettery są oznaczone jako final, dlatego nie ma potrzeby oznaczania tych getterów jako synchronized.

https://github.com/Sladamos/KingdomSimulation/blob/bb066e4c48bda88288496da95702c4e4f82f42d6/src/main/java/strategy/location/settlement/SarraxSettlement.java#L84

**Comment by Sladamos** [comment]
Poprawione
